In [2]:
import numpy as np

# Define the dataset
X = np.array([
    ['Yes', 'No', 'Mild', 'Yes', 'No'],
    ['Yes', 'Yes', 'No', 'No', 'Yes'],
    ['Yes', 'No', 'Strong', 'Yes', 'Yes'],
    ['No', 'Yes', 'Mild', 'Yes', 'Yes'],
    ['No', 'No', 'No', 'No', 'No'],
    ['No', 'Yes', 'Strong', 'Yes', 'Yes'],
    ['No', 'Yes', 'Strong', 'No', 'No'],
    ['Yes', 'Yes', 'Mild', 'Yes', 'Yes']
])

# Define the labels
y = np.array(['no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes'])

# Function to calculate class probabilities
def calculate_class_probabilities(labels):
    unique_classes, class_counts = np.unique(labels, return_counts=True)
    total_samples = len(labels)
    class_probabilities = {}
    for class_label, count in zip(unique_classes, class_counts):
        class_probabilities[class_label] = count / total_samples
    return class_probabilities

# Function to calculate conditional probabilities
def calculate_conditional_probabilities(features, labels):
    unique_features = {}
    conditional_probabilities = {}
    for feature_index in range(features.shape[1]):
        unique_feature_values, feature_value_counts = np.unique(features[:, feature_index], return_counts=True)
        unique_features[feature_index] = unique_feature_values
        conditional_probabilities[feature_index] = {}
        for class_label in np.unique(labels):
            conditional_probabilities[feature_index][class_label] = {}
            for feature_value, count in zip(unique_feature_values, feature_value_counts):
                mask = (features[:, feature_index] == feature_value) & (labels == class_label)
                conditional_probabilities[feature_index][class_label][feature_value] = np.sum(mask) / np.sum(labels == class_label)
    return conditional_probabilities, unique_features

# Function to predict the class for new data
def predict(features, class_probabilities, conditional_probabilities, unique_features):
    predicted_classes = []
    for sample in features:
        posterior_probabilities = {}
        for class_label, class_probability in class_probabilities.items():
            posterior_probability = np.log(class_probability)
            for feature_index, feature_value in enumerate(sample):
                if feature_value in unique_features[feature_index]:
                    posterior_probability += np.log(conditional_probabilities[feature_index][class_label][feature_value])
            posterior_probabilities[class_label] = posterior_probability
        predicted_class = max(posterior_probabilities, key=posterior_probabilities.get)
        predicted_classes.append(predicted_class)
    return predicted_classes

# Calculate class probabilities
class_probabilities = calculate_class_probabilities(y)

# Calculate conditional probabilities
conditional_probabilities, unique_features = calculate_conditional_probabilities(X, y)

# New data to predict
new_data = np.array(['Yes', 'No', 'Mild', 'Yes', '?'])

# Make predictions
predicted_class = predict(np.expand_dims(new_data, axis=0), class_probabilities, conditional_probabilities, unique_features)
print("Predicted class:", predicted_class[0])


Predicted class: yes


In [3]:
from sklearn.preprocessing import Normalizer
import numpy as np

# Sample data - replace this with your actual dataset
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create a normalizer object
normalizer = Normalizer()

# Fit and transform the data
normalized_data = normalizer.fit_transform(data)

# Display the normalized data
print("Normalized Data:")
print(normalized_data)


Normalized Data:
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]
